version: '3'
services:
  # Backend Services
  app-service:
    image: 'ms-book-service'
    container_name: ms-book-service
    ports:
    - 8080:8021
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb/book_micro
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=adil
      - SPRING_DATASOURCE_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - backend

  # MYSQL_SERVICE
  mysqldb:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=adil
      - MYSQL_DATABASE=book_micro
    networks:
      - backend
networks:
  backend: